from enum import StrEnum


class ProfileTier(StrEnum):
    QUICK = "quick"
    FULL = "full"


class DealState(StrEnum):
    LEAD = "LEAD"
    PRE_QUALIFYING = "PRE_QUALIFYING"
    DISQUALIFIED = "DISQUALIFIED"
    QUALIFIED = "QUALIFIED"
    ENGAGED = "ENGAGED"
    PROFILED = "PROFILED"
    MATCHING = "MATCHING"
    VEHICLE_SELECTED = "VEHICLE_SELECTED"
    FUNDING = "FUNDING"
    ACQUISITION_PENDING = "ACQUISITION_PENDING"
    ACQUIRED = "ACQUIRED"
    IN_TRANSIT = "IN_TRANSIT"
    DELIVERED = "DELIVERED"
    RETURN_PENDING = "RETURN_PENDING"
    EXCEPTION = "EXCEPTION"
    CLOSED_WON = "CLOSED_WON"
    CLOSED_LOST = "CLOSED_LOST"


class FundingState(StrEnum):
    CREDIT_APP_PENDING = "CREDIT_APP_PENDING"
    CREDIT_APP_SUBMITTED = "CREDIT_APP_SUBMITTED"
    PRE_APPROVED = "PRE_APPROVED"
    TERMS_ACCEPTED = "TERMS_ACCEPTED"
    FINAL_APPROVAL_PENDING = "FINAL_APPROVAL_PENDING"
    FULLY_FUNDED = "FULLY_FUNDED"
    CASH_BUYER = "CASH_BUYER"
    FUNDING_FAILED = "FUNDING_FAILED"


class ReturnState(StrEnum):
    RETURN_PENDING = "RETURN_PENDING"
    RETURN_IN_TRANSIT = "RETURN_IN_TRANSIT"
    RETURN_INSPECTING = "RETURN_INSPECTING"
    RETURN_APPROVED = "RETURN_APPROVED"
    RETURN_DISPUTED = "RETURN_DISPUTED"


class Actor(StrEnum):
    BUYER = "buyer"
    AGENT = "agent"
    SYSTEM = "system"
    HUMAN = "human"


class InventorySourceType(StrEnum):
    MARKETCHECK = "marketcheck"
    DEALER_PARTNER = "dealer_partner"
    DEALER_WHOLESALE = "dealer_wholesale"
    AUCTION = "auction"
    OVE = "ove"


class ImageTier(StrEnum):
    SOURCE_CACHE = "SOURCE_CACHE"
    TIER2_HERO = "TIER2_HERO"
    TIER3_PROCESSED = "TIER3_PROCESSED"
    TIER4_INSPECTION = "TIER4_INSPECTION"


class ImageContext(StrEnum):
    MARKETING = "MARKETING"
    INSPECTION = "INSPECTION"
    REFERENCE = "REFERENCE"


class ImageJobStatus(StrEnum):
    PENDING = "PENDING"
    PROCESSING = "PROCESSING"
    COMPLETED = "COMPLETED"
    FAILED = "FAILED"


class ImageDisplayMode(StrEnum):
    MARKETING = "MARKETING"
    INSPECTION_REPORT = "INSPECTION_REPORT"
    INSPECTION_PENDING = "INSPECTION_PENDING"


class InspectionStatus(StrEnum):
    NOT_STARTED = "NOT_STARTED"
    PENDING = "PENDING"
    INGESTED = "INGESTED"
    NORMALIZED = "NORMALIZED"
    VERIFIED = "VERIFIED"


class AuctionPlatform(StrEnum):
    MANHEIM = "manheim"
    OPENLANE = "openlane"
    ALLY_SMART_AUCTION = "ally-smart-auction"


class OveDetailRequestStatus(StrEnum):
    PENDING = "PENDING"
    IN_PROGRESS = "IN_PROGRESS"
    COMPLETED = "COMPLETED"
    FAILED = "FAILED"
    CANCELED = "CANCELED"
